spring:
  profiles:
    active: dev
  application:
    name: 毕业设计

# MyBatisPlus的相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      logic-delete-value: -1
      logic-not-delete-value: 0
      logic-delete-field: is_deleted
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
server:
  tomcat:
    uri-encoding: UTF-8

  servlet:
    context-path: /taian
  port: 8080

